language: node_js
node_js:
  - "12"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
scripts:
  - nohup npm run start &
  - sleep 10
  - npm run test
